"""led to 3 NF in user table

Revision ID: 33859a47576b
Revises: 36d3f3ce250a
Create Date: 2025-06-02 21:16:24.268406

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '33859a47576b'
down_revision: Union[str, None] = '36d3f3ce250a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'is_staff')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'is_staff', sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        'users',
        sa.Column(
            'full_name', sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
