"""Added id server_default

Revision ID: a8d5e7f3be0b
Revises: 33859a47576b
Create Date: 2025-07-01 17:59:45.248274

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a8d5e7f3be0b'
down_revision: Union[str, None] = '33859a47576b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";")

    op.alter_column(
        'users',
        'id',
        server_default=sa.text('uuid_generate_v4()'),
    )
    op.alter_column(
        'roles',
        'id',
        server_default=sa.text('uuid_generate_v4()'),
    )
    op.alter_column(
        'permissions',
        'id',
        server_default=sa.text('uuid_generate_v4()'),
    )

    op.alter_column('users', 'is_active', server_default=sa.text('true'))
    op.alter_column('users', 'is_verified', server_default=sa.text('false'))
    op.alter_column('users', 'created_at', server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at', server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'id',
        server_default=None,
    )
    op.alter_column(
        'roles',
        'id',
        server_default=None,
    )
    op.alter_column(
        'permissions',
        'id',
        server_default=None,
    )

    op.alter_column('users', 'is_active', server_default=None)
    op.alter_column('users', 'is_verified', server_default=None)
    op.alter_column('users', 'created_at', server_default=None)
    op.alter_column('users', 'updated_at', server_default=None)
    # ### end Alembic commands ###
